---
title: "Multiple States"
author: "Emma Landry"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(epidemia)
library(dplyr)
library(here)
library(readr)
```


```{r}
here::here()
```

```{r}
groups <- readRDS(here::here("data", "grouped_counties", "alabama_groups.rds"))
data <- readRDS(here::here("data", "covid", "prepped_epi_data.rds"))
```

```{r}
alabama_data <- filter(data, state == "AL")
```

```{r}
N <- nrow(groups)
fips <- c()
for (i in seq (1:N)){
  fips <- c(fips, unlist(groups$county_fips[i]))
}
alabama_fips <- unique (alabama_data$countyFIPS)
```

```{r}
length(sort(alabama_fips) == sort(as.double(fips)))
length(fips)
```

```{r}
a<- which(is.na(alabama_data$deaths))
alabama_data[a,]

b<- which(is.na(alabama_data$cases))
alabama_data[b,]
```

Ignore the missing data
```{r}
for (i in (seq (1:N))){
  
  #Obtaining the data
  fips <- unlist(groups$county_fips[i])
  
  if (length(fips)==1){
    data_sub <- filter(alabama_data, countyFIPS == fips)
  }else{
    data_sub <- filter(alabama_data, countyFIPS %in% fips)
    tmp <- aggregate(cbind(cases, deaths) ~ date, data=data_sub, FUN=sum)
    data_sub <- data_sub[1:314,]
    data_sub <- subset(data_sub, select = -c(countyFIPS, date,cases, deaths, state))
    data_sub <- cbind(data_sub, tmp)
    n <- nrow (data_sub)
    data_sub$county <- rep(groups$county[i], n)
  }
  
  #Doing the models
  cases_no_NA = data_sub$cases
  cases_no_NA[is.na(cases_no_NA)]=0
  idx <- which(cumsum(cases_no_NA) >= 10)[1]
  
  if (length(idx) == 0) {
    stop(paste0("Fewer than 10 cumulative cases in entire epidemic. Not modeling."))
  }
  
  start_date <- data_sub$date[idx] - 7
  data_sub <- filter(data_sub, date >= start_date)
  
  data_sub <- mutate(data_sub, week = as.integer(format(date, "%V")))
  
  pops <- data.frame("county" = groups$county[i], "population"= groups$population[i])
  
  args <- list(data= data_sub, si = EuropeCovid$si)
  
  deaths <- epiobs(
  formula = deaths(county, date) ~ 1,
  family = "neg_binom", # overdispersion for daily counts
  i2o = EuropeCovid$obs$deaths$i2o * 0.01,
  prior_intercept = rstanarm::normal(1, 0.5),
  link = "identity"
)
  
  cases <- epiobs(
  formula = cases(county, date) ~ 1,
  i2o = c(rep(0, 3), rep(1/7, 7)) * 0.2,
  family = "neg_binom",
  prior_intercept = rstanarm::normal(1, 0.5),
  link = "identity"
)
  
  args$obs <- list(deaths = deaths)
  
  args$rt <- epirt(
  formula = R(county, date) ~ rw(time=week)
)

  args$pops <- pops
  
  args$algorithm <- "sampling"
  args$pop_adjust <- FALSE
  args$init_run <- TRUE
  args$sampling_args <- list(iter = 1e3, seed=12345, chains = 1)
  
  filename <- paste0(gsub("\\s", "_", groups$county[i]), "_", "AL.rds")
  
  fit <- do.call("epim", args)

  res <- list(
    fit = fit,
    county = groups$county[i],
    state = "AL"
  )
  
  saveRDS(res, file =  here::here("epidemia_fits", "alabama", filename))
}
```

```{r}
groups <- readRDS(here::here("data", "grouped_counties", "texas_groups.rds"))
texas_data <- filter(data, state == "TX")
```

```{r}
N <- nrow(groups)
fips <- c()
for (i in seq (1:N)){
  fips <- c(fips, unlist(groups$county_fips[i]))
}
texas_fips <- unique (texas_data$countyFIPS)
```

```{r}
length(sort(texas_fips) == sort(as.double(fips)))
length(fips)
```

```{r}
a<- which(is.na(texas_data$deaths))
texas_data[a,]

b<- which(is.na(texas_data$cases))
texas_data[b,]

```
Put zero for Kaufman on 30/09 because also missing data for Rockwall on same day
```{r}
a<- which(texas_data$county == "Kaufman County" & texas_data$date == "2020-09-30")
texas_data[a,]$cases <- 0
```



```{r}
for (i in (seq (39:N)+38)){
  
  #Obtaining the data
  fips <- unlist(groups$county_fips[i])
  
  if (length(fips)==1){
    data_sub <- filter(texas_data, countyFIPS == fips)
  }else{
    data_sub <- filter(texas_data, countyFIPS %in% fips)
    tmp <- aggregate(cbind(cases, deaths) ~ date, data=data_sub, FUN=sum)
    data_sub <- data_sub[1:314,]
    data_sub <- subset(data_sub, select = -c(countyFIPS, date,cases, deaths, state))
    data_sub <- cbind(data_sub, tmp)
    n <- nrow (data_sub)
    data_sub$county <- rep(groups$county[i], n)
  }
  
  #Doing the models
  cases_no_NA = data_sub$cases
  cases_no_NA[is.na(cases_no_NA)]=0
  idx <- which(cumsum(cases_no_NA) >= 10)[1]
  
  if (length(idx) == 0) {
    stop(paste0("Fewer than 10 cumulative cases in entire epidemic. Not modeling."))
  }
  
  start_date <- data_sub$date[idx] - 7
  data_sub <- filter(data_sub, date >= start_date)
  
  data_sub <- mutate(data_sub, week = as.integer(format(date, "%V")))
  
  pops <- data.frame("county" = groups$county[i], "population"= groups$population[i])
  
  args <- list(data= data_sub, si = EuropeCovid$si)
  
  deaths <- epiobs(
  formula = deaths(county, date) ~ 1,
  family = "neg_binom", # overdispersion for daily counts
  i2o = EuropeCovid$obs$deaths$i2o * 0.01,
  prior_intercept = rstanarm::normal(1, 0.5),
  link = "identity"
)
  
  cases <- epiobs(
  formula = cases(county, date) ~ 1,
  i2o = c(rep(0, 3), rep(1/7, 7)) * 0.2,
  family = "neg_binom",
  prior_intercept = rstanarm::normal(1, 0.5),
  link = "identity"
)
  
  args$obs <- list(deaths = deaths)
  
  args$rt <- epirt(
  formula = R(county, date) ~ rw(time=week)
)

  args$pops <- pops
  
  args$algorithm <- "sampling"
  args$pop_adjust <- FALSE
  args$init_run <- TRUE
  args$sampling_args <- list(iter = 1e3, seed=12345, chains = 1)
  
  filename <- paste0(gsub("\\s", "_", groups$county[i]), "_", "TX.rds")
  
  fit <- do.call("epim", args)

  res <- list(
    fit = fit,
    county = groups$county[i],
    state = "TX"
  )
  
  saveRDS(res, file =  here::here("epidemia_fits", "texas", filename))
}
```


