---
title: "Epidemia Plots"
author: "Emma Landry"
date: "6/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(epidemia)
library(dplyr)
library(here)
library(readr)
library(readxl)
library(rstan)
library(ggplot2)
library(GGally)
library(reshape2) #for melt
library(urbnmapr)
library(tidyverse)
library(rstanarm)
library(bayesplot)
library(cowplot)
```

ELECTIONS ARE WEEK 45

```{r}
alabama <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/alabama_3395374[1].pbs.rds")
```

```{r}
alabama_rt <- posterior_rt(alabama$fit)
```

```{r}
alabama_summary <- summary((alabama$fit)$stanfit)$summary
alabama_summary[,9:10]
alabama_summary
```

```{r}
rownames(alabama_summary)
```


```{r}
index <- (rownames(alabama_summary)=="R|rw(time = week)[45,all]")
```

```{r}
color_scheme_set("mix-blue-red")
mcmc_trace((alabama$fit)$stanfit, par = rownames(alabama_summary)[index])+
  ggtitle("Alabama")+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
```



```{r}
data <- readRDS(here::here("data", "covid", "prepped_data_state.rds"))
```


```{r}
california <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/california_3395374[5].pbs.rds")
```

```{r}
california_rt <- posterior_rt(california$fit)
```

```{r}
california_summary <- summary((california$fit)$stanfit)$summary
california_summary[,9:10]
```

```{r}
file_list <- list.files(path= "/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1")
file_list<- file_list[-2]
file_list
```

```{r}
long_state <- c("Alabama", "Arizona", "Arkansas", "California", "Colorado", "Connecticut",
                "Delaware", "Florida", "Georgia", "Idaho", "Illinois","Indiana","Iowa", "Kansas",
                "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan",
                "Minnesota", "Mississippi", "Missouri","Montana", "Nebraska", "Nevada","New Hampshire","New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
                "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
                "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
                "West Virginia","Wisconsin", "Wyoming")
```


```{r}
for (i in seq(1:48)){
  path <- paste0("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/", file_list[i])
  model <- readRDS(path)
  
  model_rt <- posterior_rt(model$fit)
  model_summary <- summary((model$fit)$stanfit)$summary
  index <- (rownames(model_summary)=="R|rw(time = week)[45,all]")
  color_scheme_set("mix-blue-red")

  
  mcmc_trace((model$fit)$stanfit, par = rownames(model_summary)[index], 
             transformations = "exp")+
  ggtitle(long_state[i])+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
  ggsave(paste0(long_state[i],"_traceplot.pdf"), height = 4, scale = 1)
  
}

```
richardson, nemaha, pawnee, johnson, otoe, gage, dodge, sauners, cass Nebraska 83 
Ohio 45

```{r}
santa_barbara<- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/Santa_Barbara_County_CA_3572195[5].pbs.rds")
```

```{r}
dallas <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/Dallas_County_TX_3572195[42].pbs.rds")
```

```{r}
nebraska83 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/Group_83_NE_3572195[26].pbs.rds")
```

```{r}
ohio45 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/Group_45_OH_3572195[34].pbs.rds")
```

```{r}
newyork_1 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/new_york_3395374[31].pbs.rds")
```


```{r}
indiana_1 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/indiana_3395374[13].pbs.rds")
```

```{r}
kansas_1 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/kansas_3395374[15].pbs.rds")
```

```{r}
virginia_1 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/virginia_3395374[45].pbs.rds")
```

```{r}
newyork_2 <- readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/convergence_check/new_york_3711248[2].pbs.rds")
```

```{r}
indiana_2<-  readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/convergence_check/indiana_3711248[1].pbs.rds")
```

```{r}
kansas_2 <-  readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/convergence_check/kansas_3711248[4].pbs.rds")
```

```{r}
virginia_2 <-  readRDS("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/convergence_check/virginia_3711248[3].pbs.rds")
```


```{r}
santa_barbara_rt <- posterior_rt(santa_barbara$fit)
santa_barbara_summary <- summary((santa_barbara$fit)$stanfit)$summary

dallas_rt <- posterior_rt(dallas$fit)
dallas_summary <- summary((dallas$fit)$stanfit)$summary 

nebraska83_rt <- posterior_rt(nebraska83$fit)
nebraska83_summary <- summary((nebraska83$fit)$stanfit)$summary

ohio45_rt <- posterior_rt(ohio45$fit)
ohio45_summary <- summary((ohio45$fit)$stanfit)$summary
```

```{r}
index <- (rownames(santa_barbara_summary)=="R|rw(time = week)[45,all]")
santa_barbara_summary[,9:10][index]

index <- (rownames(dallas_summary)=="R|rw(time = week)[45,all]")
dallas_summary[,9:10][index]

index <- (rownames(nebraska83_summary)=="R|rw(time = week)[45,all]")
nebraska83_summary[,9:10][index]

index <- (rownames(ohio45_summary)=="R|rw(time = week)[45,all]")
ohio45_summary[,9:10][index]
```



```{r}
newyork_1_rt <- posterior_rt(newyork_1$fit)
newyork_1_summary <- summary((newyork_1$fit)$stanfit)$summary

indiana_1_rt <- posterior_rt(indiana_1$fit)
indiana_1_summary <- summary((indiana_1$fit)$stanfit)$summary 

kansas_1_rt <- posterior_rt(kansas_1$fit)
kansas_1_summary <- summary((kansas_1$fit)$stanfit)$summary

virginia_1_rt <- posterior_rt(virginia_1$fit)
virginia_1_summary <- summary((virginia_1$fit)$stanfit)$summary
```



```{r}
index <- (rownames(newyork_1_summary)=="R|rw(time = week)[45,all]")
newyork_1_summary[,9:10][index]
exp(newyork_1_summary[index][c(4,6,8)])

index <- (rownames(indiana_1_summary)=="R|rw(time = week)[45,all]")
indiana_1_summary[,9:10][index]
exp(indiana_1_summary[index][c(4,6,8)])

index <- (rownames(kansas_1_summary)=="R|rw(time = week)[45,all]")
kansas_1_summary[,9:10][index]
exp(kansas_1_summary[index][c(4,6,8)])


index <- (rownames(virginia_1_summary)=="R|rw(time = week)[45,all]")
virginia_1_summary[,9:10][index]
exp(virginia_1_summary[index][c(4,6,8)])

```


```{r}
#newyork_2_rt <- posterior_rt(newyork_2$fit)
#newyork_2_summary <- summary((newyork_2$fit)$stanfit)$summary

#indiana_2_rt <- posterior_rt(indiana_2$fit)
#indiana_2_summary <- summary((indiana_2$fit)$stanfit)$summary 

kansas_2_rt <- posterior_rt(kansas_2$fit)
kansas_2_summary <- summary((kansas_2$fit)$stanfit)$summary

#virginia_2_rt <- posterior_rt(virginia_2$fit)
#virginia_2_summary <- summary((virginia_2$fit)$stanfit)$summary
```


```{r}
#index <- (rownames(newyork_2_summary)=="R|rw(time = week)[45,all]")
#newyork_2_summary[,9:10][index]
#exp(newyork_2_summary[index][c(4,6,8)])


#index <- (rownames(indiana_2_summary)=="R|rw(time = week)[45,all]")
#indiana_2_summary[,9:10][index]
#exp(indiana_2_summary[index][c(4,6,8)])

index <- (rownames(kansas_2_summary)=="R|rw(time = week)[45,all]")
kansas_2_summary[,9:10][index]
exp(kansas_2_summary[index][c(4,6,8)])

#index <- (rownames(virginia_2_summary)=="R|rw(time = week)[45,all]")
#virginia_2_summary[,9:10][index]
#exp(virginia_2_summary[index][c(4,6,8)])
```

```{r}
santa_barbara_rt <- posterior_rt(santa_barbara$fit)
  santa_barbara_summary <- summary((santa_barbara$fit)$stanfit)$summary
  index <- (rownames(santa_barbara_summary)=="R|rw(time = week)[45,all]")
  
  color_scheme_set("mix-blue-red")
  mcmc_trace((santa_barbara$fit)$stanfit, par = rownames(santa_barbara_summary)[index], 
             transformations = "exp")+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
  ggsave(paste0("santa_barbara","_traceplot.pdf"), height = 4, scale = 1)
```

```{r}
dallas_rt <- posterior_rt(dallas$fit)
  dallas_summary <- summary((dallas$fit)$stanfit)$summary
  index <- (rownames(dallas_summary)=="R|rw(time = week)[45,all]")
  
  color_scheme_set("mix-blue-red")
  mcmc_trace((dallas$fit)$stanfit, par = rownames(dallas_summary)[index], 
             transformations = "exp")+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
  ggsave(paste0("dallas","_traceplot.pdf"), height = 4, scale = 1)
```

```{r}
nebraska83_rt <- posterior_rt(nebraska83$fit)
  nebraska83_summary <- summary((nebraska83$fit)$stanfit)$summary
  index <- (rownames(nebraska83_summary)=="R|rw(time = week)[45,all]")
  
  color_scheme_set("mix-blue-red")
  mcmc_trace((nebraska83$fit)$stanfit, par = rownames(nebraska83_summary)[index], 
             transformations = "exp")+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
  ggsave(paste0("nebraska83","_traceplot.pdf"), height = 4, scale = 1)
```

```{r}
ohio45_rt <- posterior_rt(ohio45$fit)
  ohio45_summary <- summary((ohio45$fit)$stanfit)$summary
  index <- (rownames(ohio45_summary)=="R|rw(time = week)[45,all]")
  
  color_scheme_set("mix-blue-red")
  mcmc_trace((ohio45$fit)$stanfit, par = rownames(ohio45_summary)[index], 
             transformations = "exp")+
  theme_bw()+
  theme(text = element_text(family = "sans"),
        plot.title = element_text(hjust = 0.5, size = 15))+
  labs(x = "Iteration", y = "Rt- Week 45")
  ggsave(paste0("ohio45","_traceplot.pdf"), height = 4, scale = 1)
```

```{r}
convergence_states_week45 <- data.frame(matrix(ncol = 3, nrow = 48))
convergence_states_week45[,1]<- long_state
colnames(convergence_states_week45)<- c("State", "Effective Sample Size", "Rhat")
```


```{r}
for (i in seq(1:48)){
  path <- paste0("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/state1/", file_list[i])
  model <- readRDS(path)
  
  model_rt <- posterior_rt(model$fit)
  model_summary <- summary((model$fit)$stanfit)$summary
  index <- (rownames(model_summary)=="R|rw(time = week)[45,all]")
  convergence_states_week45[i,2:3] <- model_summary[,9:10][index]
}

```

```{r}
santa_barbara_names <- rownames(santa_barbara_summary)
santa_barbara_names <- santa_barbara_names[-1]
santa_barbara_names <- santa_barbara_names[1:(length(santa_barbara_names)-6)]
santa_barbara_weeks <- (67-length(santa_barbara_names)):66
santa_barbara_df<- data.frame(matrix(ncol = 3, nrow = length(santa_barbara_weeks)))
colnames(santa_barbara_df)<- c("Week", "ESS", "Rhat")
santa_barbara_df$Week <- santa_barbara_weeks
santa_barbara_df[,2]<- as.numeric(santa_barbara_summary[2: (length(santa_barbara_weeks)+1), 9])
santa_barbara_df[,3]<- as.numeric(santa_barbara_summary[2: (length(santa_barbara_weeks)+1), 10])
```

```{r}
dallas_names <- rownames(dallas_summary)
dallas_names <- dallas_names[-1]
dallas_names <- dallas_names[1:(length(dallas_names)-6)]
dallas_weeks <- (67-length(dallas_names)):66
dallas_df<- data.frame(matrix(ncol = 3, nrow = length(dallas_weeks)))
colnames(dallas_df)<- c("Week", "ESS", "Rhat")
dallas_df$Week <- dallas_weeks
dallas_df[,2]<- as.numeric(dallas_summary[2: (length(dallas_weeks)+1), 9])
dallas_df[,3]<- as.numeric(dallas_summary[2: (length(dallas_weeks)+1), 10])
```

```{r}
nebraska83_names <- rownames(nebraska83_summary)
nebraska83_names <- nebraska83_names[-1]
nebraska83_names <- nebraska83_names[1:(length(nebraska83_names)-6)]
nebraska83_weeks <- (67-length(nebraska83_names)):66
nebraska83_df<- data.frame(matrix(ncol = 3, nrow = length(nebraska83_weeks)))
colnames(nebraska83_df)<- c("Week", "ESS", "Rhat")
nebraska83_df$Week <- nebraska83_weeks
nebraska83_df[,2]<- as.numeric(nebraska83_summary[2: (length(nebraska83_weeks)+1), 9])
nebraska83_df[,3]<- as.numeric(nebraska83_summary[2: (length(nebraska83_weeks)+1), 10])
```

```{r}
ohio45_names <- rownames(ohio45_summary)
ohio45_names <- ohio45_names[-1]
ohio45_names <- ohio45_names[1:(length(ohio45_names)-6)]
ohio45_weeks <- (67-length(ohio45_names)):66
ohio45_df<- data.frame(matrix(ncol = 3, nrow = length(ohio45_weeks)))
colnames(ohio45_df)<- c("Week", "ESS", "Rhat")
ohio45_df$Week <- ohio45_weeks
ohio45_df[,2]<- as.numeric(ohio45_summary[2: (length(ohio45_weeks)+1), 9])
ohio45_df[,3]<- as.numeric(ohio45_summary[2: (length(ohio45_weeks)+1), 10])
```

```{r}
ggplot()+
  geom_line(data= santa_barbara_df, aes (x= Week, y = Rhat, color = "Santa Barbara, California"))+
  geom_line(data = dallas_df, aes (x= Week, y = Rhat, color = "Dallas, Texas"))+
  geom_line(data = nebraska83_df, aes (x= Week, y = Rhat, color = "Group, Nebraska"))+
  geom_line(data = ohio45_df, aes (x= Week, y = Rhat, color = "Group, Ohio"))+
    guides(color=guide_legend(ncol=2))+
  scale_color_manual(values=c("#F8766D", "#00BFC4", "#C77CFF", "#529EFF" ))+
  theme_bw()+
  labs(color = "County")+
  scale_x_continuous(limits = c(10,66), expand = c(0, 0)) +
  theme(
    legend.position = c(.25, .9),
    legend.background = element_rect(fill = "transparent"),
    legend.key = element_rect(fill = "transparent", colour = "transparent"))


ggsave("rhatcountyplot.pdf", height = 4, scale = 1)
```

```{r}
file_list_county <- list.files(path= "/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6")
```

```{r}
short_file_list <- file_list_county[1:400]
numbers <- 1:400
index <- numbers%%2 ==0
file_list_final <- c(short_file_list[index],file_list_county[401])

short_file_list <- file_list_county[402:415]
numbers <- 1:14
index <- numbers%%2 ==0
file_list_final <- c(file_list_final, short_file_list[index], file_list_county[416:418])

short_file_list <- file_list_county[419:1594]
numbers <- 1:1176
index <- numbers%%2 ==0

file_list_final <- c(file_list_final, short_file_list[index])
```


```{r}
convergence_county_week45 <- data.frame(matrix(ncol = 3, nrow = 799))
colnames(convergence_county_week45) <- c("File", "ESS", "Rhat")
convergence_county_week45$File <- file_list_final
```

```{r}
for (i in seq(1:799)){
  print(i)
  path <- paste0("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/", file_list_final[i])
  model <- readRDS(path)
  
  model_summary <- summary((model$fit)$stanfit)$summary
  index <- (rownames(model_summary)=="R|rw(time = week)[45,all]")
  convergence_county_week45[i,2:3] <- model_summary[,9:10][index]
}
```


```{r}
for (i in 486:799){
  print(i)
  path <- paste0("/Volumes/evl17/home/Msc/Outputs/epidemia_fits/run6/", file_list_final[i])
  model <- readRDS(path)
  
  model_summary <- summary((model$fit)$stanfit)$summary
  index <- (rownames(model_summary)=="R|rw(time = week)[45,all]")
  convergence_county_week45[i,2:3] <- model_summary[,9:10][index]
  
}
```

```{r}
convergence_county_week45 <- readRDS("/Users/emmalandry/Documents/Imperial/Year 4/M4R/m4r-repo/countyconvergence.rds")
```


```{r}
ess_hist2<- convergence_county_week45 %>% 
  mutate(x_new = ifelse(ESS > 3000, 3000, ESS)) %>% 
  ggplot(aes(x_new)) +
  geom_histogram(binwidth = 50, col = "black", fill = "#F8766D")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500, 2000, 2500, 3000),
    labels = c("0", "500", "1000", "1500", "2000", "2500", "3000+"),
    limits = c(0,3100), expand = c(0, 0))+
  labs (x = "Effective Sample Size", y= "Count")+
  theme_bw()+
  geom_vline(xintercept = 100, linetype = "dashed", color = "black")+
  scale_y_continuous(limits = c(0,70), expand = c(0, 0))
ess_hist2
```


```{r}
ess_hist1<- ggplot(data= convergence_county_week45, aes (x= ESS))+
  geom_histogram(binwidth = 100, color = 'black', fill="#F8766D" )+
  labs (x = "Effective Sample Size", y= "Count")+
  theme_bw()+
  geom_vline(xintercept = 100, linetype = "dashed", color = "black")+
scale_x_continuous(limits = c(-100,6500), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,55), expand = c(0, 0))
ess_hist1
```


```{r}
title <- ggdraw() + draw_label("Week 45 Rt ESS, for the 797 counties", fontface='bold')
p<- plot_grid(ess_hist1, ess_hist2, ncol = 2, nrow = 1)
#plot_grid(title, p, ncol =1,rel_heights=c(0.1, 1))
p
ggsave("ess_hist.pdf", height = 4, width = 10)
```


```{r}
rhat_hist1<- ggplot(data= convergence_county_week45, aes (x= Rhat))+
  geom_histogram(binwdith = 0.05/9, color = 'black', fill="#F8766D" )+
  labs (x = "Rhat", y= "Count")+
  theme_bw()+
  scale_x_continuous(limits = c(0.995,NA), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,500), expand = c(0, 0))
rhat_hist1
```


```{r}
rhat_hist2<- convergence_county_week45 %>% 
  mutate(x_new = ifelse(Rhat > 1.05, 1.05, Rhat)) %>% 
  ggplot(aes(x_new)) +
  geom_histogram(col = "black", fill = "#F8766D", binwidht = 0.02)+
  labs (x = "Rhat", y= "Count")+
  theme_bw()+
  scale_x_continuous(limits = c(0.998,1.052), expand = c(0, 0),
                     breaks = c(1, 1.01, 1.02, 1.03, 1.04, 1.05),
    labels = c("1.00", "1.01", "1.02", "1.03", "2.04", "1.05+")) +
  scale_y_continuous(limits = c(0,225), expand = c(0, 0))
rhat_hist2
```

```{r}
title1 <- ggdraw() + draw_label("Week 45 Rt Rhat, for the 797 counties", fontface='bold')
p1<- plot_grid(rhat_hist1, rhat_hist2, ncol = 2, nrow = 1)
p1
#plot_grid(title, p1, ncol =1,rel_heights=c(0.1, 1))
ggsave("rhat_hist.pdf", height = 4, width = 10)
```

